# Generated by Django 4.2.11 on 2026-03-05 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Course Name / 课程名称')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course / 课程',
                'verbose_name_plural': 'Courses / 课程',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='train_engine.course')),
            ],
            options={
                'verbose_name': 'Lesson / 章节',
                'verbose_name_plural': 'Lessons / 章节',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='train_engine.lesson')),
            ],
            options={
                'verbose_name': 'Sentence / 句子',
                'verbose_name_plural': 'Sentences / 句子',
            },
        ),
    ]
