# Generated by Django 4.2.11 on 2026-03-01 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=200, verbose_name='Course Name / 课程名称')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Course / 课程',
                'verbose_name_plural': 'Courses / 课程',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.course')),
            ],
            options={
                'verbose_name': 'Lesson / 章节',
                'verbose_name_plural': 'Lessons / 章节',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Word / 单词')),
                ('meaning_en', models.TextField(blank=True, verbose_name='Meaning (EN) / 英文释义')),
                ('meaning_zh', models.TextField(blank=True, verbose_name='Meaning (ZH) / 中文释义')),
                ('meaning_ja', models.TextField(blank=True, verbose_name='Meaning (JA) / 日本語意味')),
            ],
            options={
                'verbose_name': 'Word / 单词',
                'verbose_name_plural': 'Words / 单词',
            },
        ),
        migrations.CreateModel(
            name='StudyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(default=False)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.word')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(verbose_name='English Sentence / 英文句子')),
                ('text_zh', models.TextField(blank=True, verbose_name='Chinese Translation / 中文翻译')),
                ('text_ja', models.TextField(blank=True, verbose_name='Japanese / 日本語')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_engine.lesson')),
            ],
            options={
                'verbose_name': 'Sentence / 句子',
                'verbose_name_plural': 'Sentences / 句子',
            },
        ),
    ]
