# Generated by Django 4.2.11 on 2026-03-08 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceoption',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Choice Option / 选择题选项', 'verbose_name_plural': 'Choice Options / 选择题选项'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id'], 'verbose_name': 'Course / 课程', 'verbose_name_plural': 'Courses / 课程'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Lesson / 章节', 'verbose_name_plural': 'Lessons / 章节'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Question / 题目', 'verbose_name_plural': 'Questions / 题目'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Sentence / 句子', 'verbose_name_plural': 'Sentences / 句子'},
        ),
        migrations.AlterModelOptions(
            name='studylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Log / 学习记录', 'verbose_name_plural': 'Study Logs / 学习记录'},
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='是否系统补齐'),
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='课程英文名'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='章节英文标题'),
        ),
        migrations.AddField(
            model_name='question',
            name='blank_mode',
            field=models.CharField(choices=[('auto', '自动挖空'), ('specified', '指定挖空')], default='auto', max_length=20, verbose_name='挖空方式'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='是否自动生成'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False, verbose_name='是否多选'),
        ),
        migrations.AddField(
            model_name='question',
            name='manual_distractors',
            field=models.TextField(blank=True, null=True, verbose_name='人工混淆项（每行一个）'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_count',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='总选项数'),
        ),
        migrations.AddField(
            model_name='question',
            name='pattern',
            field=models.TextField(blank=True, null=True, verbose_name='句型提示 / Pattern'),
        ),
        migrations.AddField(
            model_name='question',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='音频'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='难度等级'),
        ),
        migrations.AddField(
            model_name='sentence',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='train_engine.sentence', verbose_name='所属句子'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='是否正确'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='train_engine.question', verbose_name='所属题目'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='text',
            field=models.CharField(max_length=200, verbose_name='选项内容'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='课程描述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='train_engine.course', verbose_name='所属课程'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='章节标题'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='音频文件'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='question',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='train_engine.sentence', verbose_name='所属句子'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='train_engine.lesson', verbose_name='所属章节'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='text',
            field=models.TextField(verbose_name='原句'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.TextField(blank=True, verbose_name='翻译'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='是否正确'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='记录时间'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='memory_level',
            field=models.IntegerField(default=0, help_text='0-6 记忆等级', verbose_name='记忆等级'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习时间'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='train_engine.question', verbose_name='所属题目'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='user_input',
            field=models.TextField(blank=True, verbose_name='用户输入'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='wrong_count',
            field=models.IntegerField(default=0, verbose_name='错误次数'),
        ),
    ]
