# Generated by Django 4.2.11 on 2026-03-12 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0002_alter_choiceoption_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='letter',
            field=models.CharField(blank=True, max_length=1, verbose_name='选项字母'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='normalized_answer',
            field=models.TextField(blank=True, verbose_name='标准化答案'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='normalized_input',
            field=models.TextField(blank=True, verbose_name='标准化输入'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='similarity',
            field=models.FloatField(default=0, verbose_name='相似度'),
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='is_auto_generated',
            field=models.BooleanField(default=False, verbose_name='系统生成'),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/', verbose_name='题目音频'),
        ),
        migrations.AlterField(
            model_name='question',
            name='manual_distractors',
            field=models.TextField(blank=True, null=True, verbose_name='人工混淆项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_count',
            field=models.PositiveSmallIntegerField(default=4, verbose_name='选项数量'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pattern',
            field=models.TextField(blank=True, null=True, verbose_name='句型提示'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='memory_level',
            field=models.IntegerField(default=0, verbose_name='记忆等级'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='train_engine.question'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='train_engine.sentence'),
        ),
        migrations.CreateModel(
            name='WrongQuestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField(blank=True, verbose_name='错误输入')),
                ('wrong_count', models.IntegerField(default=1, verbose_name='错误次数')),
                ('last_wrong', models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后错误')),
                ('is_mastered', models.BooleanField(default=False, verbose_name='已掌握')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wrong_logs', to='train_engine.question')),
            ],
            options={
                'verbose_name': 'Wrong Question / 错题',
                'verbose_name_plural': 'Wrong Questions / 错题',
                'ordering': ['-last_wrong'],
            },
        ),
    ]
