# Generated by Django 4.2.11 on 2026-03-07 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0002_studylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Log / 学习记录', 'verbose_name_plural': 'Study Logs / 学习记录'},
        ),
        migrations.AddField(
            model_name='studylog',
            name='memory_level',
            field=models.IntegerField(default=0, help_text='0-6 记忆等级'),
        ),
        migrations.AddField(
            model_name='studylog',
            name='next_review',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studylog',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_logs', to='train_engine.sentence'),
        ),
        migrations.AlterField(
            model_name='studylog',
            name='user_input',
            field=models.TextField(blank=True),
        ),
    ]
