# Generated by Django 4.2.11 on 2026-03-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0003_choiceoption_letter_studylog_normalized_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否隐藏知识点'),
        ),
        migrations.CreateModel(
            name='UserMemoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_level', models.IntegerField(default=0, verbose_name='记忆等级')),
                ('next_review', models.DateTimeField(blank=True, null=True, verbose_name='下次复习')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='上次复习')),
                ('cycle_started', models.DateTimeField(blank=True, null=True, verbose_name='循环开始时间')),
                ('wrong_reset_count', models.IntegerField(default=0, verbose_name='错误重置次数')),
                ('overdue_reset_count', models.IntegerField(default=0, verbose_name='过期重置次数')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('mastered_at', models.DateTimeField(blank=True, null=True, verbose_name='掌握时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_states', to='train_engine.sentence', verbose_name='所属句子')),
            ],
            options={
                'verbose_name': 'User Memory State / 当前记忆状态',
                'verbose_name_plural': 'User Memory States / 当前记忆状态',
                'ordering': ['sentence_id'],
            },
        ),
    ]
