# Generated by Django 4.2.11 on 2026-03-15 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train_engine', '0004_sentence_is_active_usermemorystate'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMemoryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='单词')),
                ('normalized_word', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='标准化单词')),
                ('memory_level', models.IntegerField(default=0, verbose_name='记忆等级')),
                ('next_review', models.DateTimeField(blank=True, null=True, verbose_name='下次复习')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='上次复习')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('review_count', models.IntegerField(default=0, verbose_name='复习次数')),
                ('is_due_boost', models.BooleanField(default=False, verbose_name='是否错词强化中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_memories', to='train_engine.sentence', verbose_name='来源句子')),
            ],
            options={
                'verbose_name': 'Word Memory State / 单词记忆状态',
                'verbose_name_plural': 'Word Memory States / 单词记忆状态',
                'ordering': ['normalized_word'],
            },
        ),
    ]
