# Generated by Django 4.2.11 on 2026-03-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_alter_trainingitem_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmemory',
            name='last_wrong_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='wrong_boost',
            field=models.IntegerField(default=0),
        ),
    ]
