# Generated by Django 4.2.11 on 2026-03-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_questionmemory_last_wrong_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionmemory',
            name='item',
        ),
    ]
