# Generated by Django 4.2.11 on 2026-03-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_remove_questionmemory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmemory',
            name='cycle_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='cycle_step',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='cycle_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='last_reset_reason',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='last_result',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='questionmemory',
            name='mastered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
