# Generated by Django 4.2.11 on 2026-04-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0005_questionmemory_cycle_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='accepted_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='answer_type',
            field=models.CharField(choices=[('translation', '翻译'), ('polite_expression', '敬语表达'), ('tense_person_conversion', '时态/人称转换'), ('literary_expression', '文学表达'), ('fixed_expression', '固定表达'), ('general_response', '一般回答')], default='general_response', max_length=50),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='auto_cloze_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='cloze_mode',
            field=models.CharField(choices=[('manual_only', '仅人工克漏字'), ('auto_only', '仅自动克漏字'), ('manual_first', '人工优先，自动补充')], default='manual_first', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='enabled_modes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='grading_mode',
            field=models.CharField(choices=[('strict', '严格匹配'), ('normalize', '归一化匹配'), ('multi_answer', '多答案匹配'), ('keyword', '关键词匹配')], default='normalize', max_length=30),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='instruction_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='language',
            field=models.CharField(choices=[('ja', '日语'), ('en', '英语'), ('zh', '中文'), ('mixed', '混合')], default='ja', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='manual_cloze_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='source_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/source/'),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='source_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='target_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='target_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/target/'),
        ),
    ]
