# Generated by Django 4.2.11 on 2026-04-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_studylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='answer_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/answers/'),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='answer_use_tts',
            field=models.BooleanField(default=False),
        ),
    ]
