# Generated by Django 4.2.11 on 2026-04-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0008_trainingitem_answer_audio_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('cloze_blank', 'Cloze Blank')], default='cloze_blank', max_length=30)),
                ('source_index', models.PositiveSmallIntegerField(default=0)),
                ('token_text', models.CharField(max_length=255)),
                ('token_norm', models.CharField(db_index=True, max_length=255)),
                ('memory_level', models.IntegerField(default=0)),
                ('cycle_step', models.PositiveSmallIntegerField(default=0)),
                ('cycle_started_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_version', models.PositiveIntegerField(default=1)),
                ('mastered_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=20)),
                ('last_reset_reason', models.CharField(blank=True, default='', max_length=30)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('correct_streak', models.IntegerField(default=0)),
                ('total_correct', models.IntegerField(default=0)),
                ('total_wrong', models.IntegerField(default=0)),
                ('last_review_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_memories', to='train.question')),
                ('training_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='word_memories', to='train.trainingitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review_at', 'id'],
                'unique_together': {('user', 'question', 'source_type', 'source_index', 'token_norm')},
            },
        ),
    ]
