# Generated by Django 4.2.11 on 2026-04-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0009_wordmemory'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='prompt_image_file',
            field=models.FileField(blank=True, null=True, upload_to='images/prompts/'),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='prompt_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
