# Generated by Django 4.2.11 on 2026-05-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0010_trainingitem_prompt_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='practice/audio/')),
                ('source_url', models.URLField(blank=True, default='')),
                ('original_bpm', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_tracks', to=settings.AUTH_USER_MODEL)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='train.practiceplaylist')),
            ],
            options={
                'ordering': ['playlist', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticeSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('start_time', models.FloatField(default=0)),
                ('end_time', models.FloatField(default=0)),
                ('start_speed', models.FloatField(default=0.7)),
                ('end_speed', models.FloatField(default=1.0)),
                ('speed_step', models.FloatField(default=0.05)),
                ('repeat_per_step', models.PositiveIntegerField(default=3)),
                ('end_mode', models.CharField(choices=[('stop', '到目标后停止'), ('keep', '到目标后保持'), ('repeat', '回到起始速度'), ('step_down', '到目标后步退'), ('ping_pong', '往返循环')], default='step_down', max_length=20)),
                ('preserve_pitch', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_segments', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='train.practicetrack')),
            ],
            options={
                'ordering': ['track', 'sort_order', 'id'],
            },
        ),
    ]
