# Generated by Django 4.2.11 on 2026-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_practiceplaylist_practicetrack_practicesegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicetrack',
            name='shadow_caption_source',
            field=models.TextField(blank=True, default=''),
        ),
    ]
