# Generated by Django 4.2.11 on 2026-05-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_practicetrack_shadow_caption_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='dictation_text',
            field=models.TextField(blank=True, default='', help_text='专门用于听写播放和 TTS 生成的文本'),
        ),
        migrations.AddField(
            model_name='trainingitem',
            name='is_dictation_enabled',
            field=models.BooleanField(default=False, help_text='是否允许该写作训练题进入听写考核'),
        ),
    ]
