# Generated by Django 4.2.11 on 2026-05-12 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0013_trainingitem_dictation_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('book', '书册'), ('lesson', '课节')], max_length=20)),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('finished', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_sessions', to='train.book')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_sessions', to='train.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DictationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('dictation_text_snapshot', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('correct_attempt_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user_answers', models.JSONField(blank=True, default=list)),
                ('timed_out', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_results', to='train.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='train.dictationsession')),
                ('training_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dictation_results', to='train.trainingitem')),
            ],
            options={
                'ordering': ['session', 'order_index', 'id'],
            },
        ),
    ]
