# Generated by Django 4.2.11 on 2026-05-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_dictationsession_dictationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictationresult',
            name='dictation_field_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='dictationresult',
            name='dictation_field_label',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
