# Generated by Django 4.2.11 on 2026-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0015_dictationresult_dictation_field_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='sequence_chunks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
