# Generated by Django 4.2.11 on 2026-06-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0016_trainingitem_sequence_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
