# Generated by Django 4.2.11 on 2026-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_lesson_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
