# Generated by Django 4.2.11 on 2026-07-20 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0018_alter_question_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingitem',
            name='memory_item',
            field=models.ForeignKey(blank=True, help_text='该训练题所属的核心知识点；旧数据可暂时留空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_items', to='train.memoryitem'),
        ),
    ]
