# Generated by Django 4.2.11 on 2026-07-21 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0019_trainingitem_memory_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryItemVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('learning', '学习中'), ('ready', '待毕业验证'), ('verified', '已验证掌握')], default='learning', max_length=20)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='train.memoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_item_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='memoryitemverification',
            constraint=models.UniqueConstraint(fields=('user', 'memory_item'), name='unique_user_memory_item_verification'),
        ),
    ]
