# Generated by Django 4.2.11 on 2026-07-21 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('train', '0020_memoryitemverification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.PositiveSmallIntegerField(default=0)),
                ('correct_count', models.PositiveSmallIntegerField(default=0)),
                ('wrong_count', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', '进行中'), ('finished', '已完成'), ('abandoned', '已放弃')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_sessions', to='train.memoryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_sessions', to=settings.AUTH_USER_MODEL)),
                ('verification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_sessions', to='train.memoryitemverification')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('item_type_snapshot', models.CharField(blank=True, default='', max_length=30)),
                ('instruction_text_snapshot', models.TextField(blank=True, default='')),
                ('source_text_snapshot', models.TextField(blank=True, default='')),
                ('target_answer_snapshot', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user_answer', models.JSONField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_results', to='train.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='train.graduationsession')),
                ('training_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graduation_results', to='train.trainingitem')),
            ],
            options={
                'ordering': ['session', 'order_index', 'id'],
            },
        ),
    ]
